# Generated by Django 5.2.4 on 2025-08-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articel',
            new_name='article',
        ),
    ]
